// ─── Adult Red Dragon sprite sheet ────────────────────────────────────────────
// Loads dragon-sheet.png and hands render-enemies.js a single blit in place of
// the ~240 lines of procedural art in `case 'adult_red_dragon'`. Generated by
// tools/make-dragon-sheet.lua.
//
// Same rules as hero-sprite.js: the layout is hardcoded rather than read from
// dragon-sheet.json, because fetch/XHR cannot reach a sibling file over file://.
// Change the generator and these constants together. Loading is async and
// failure is survivable — the procedural art stays in place as the fallback.
//
// Only the creature is baked in. The soft additive FX around it (boss aura,
// chest furnace, rising embers, nostril smoke) stay procedural so they keep
// their own periods and alpha — see the helpers in render-enemies.js.

const DRAGON_SHEET_SRC = 'dragon-sheet.png';
const DRAGON_FRAME     = 168;   // frame box in the sheet, px
const DRAGON_BODY      = 134;   // body box inside it == ts * e.size (2.8 tiles)
const DRAGON_BODY_O    = 17;    // body box origin inside the frame
const DRAGON_COLS      = 6;     // 36 frames laid out 6x6

// How long the breath animation plays once the flame fan spawns. Also used by
// projectiles.js to set e.breathT — keep the two in step.
const DRAGON_BREATH_ANIM_MS = 540;

// anim -> [startIndex, frameCount, msPerFrame], indices running left-to-right,
// top-to-bottom across the 6x6 grid.
const DRAGON_ANIMS = {
  dormant: [0,  4, 220],
  awake:   [4,  8, 100],   // stationary hover
  fly:     [12, 6,  90],
  run:     [18, 6,  80],
  breathe: [24, 6,  90],   // 6 * 90 == DRAGON_BREATH_ANIM_MS
  fight:   [30, 6,  70],
};

// Distance thresholds (tiles) for picking a locomotion animation.
const DRAGON_MELEE_RANGE = 2.4;   // inside this he claws rather than travels
const DRAGON_FLY_RANGE   = 6.0;   // beyond this he crosses the hall on the wing

let dragonSheetImg   = null;
let dragonSheetState = 'idle';   // 'idle' | 'loading' | 'ready' | 'error'

function ensureDragonSheet() {
  if (dragonSheetImg) return;
  dragonSheetImg = new Image();
  dragonSheetState = 'loading';
  dragonSheetImg.onload  = () => { dragonSheetState = 'ready'; };
  dragonSheetImg.onerror = () => { dragonSheetState = 'error'; };
  dragonSheetImg.src = DRAGON_SHEET_SRC;
}

function dragonSheetReady() {
  ensureDragonSheet();
  return dragonSheetState === 'ready';
}

// Movement is inferred rather than flagged: nothing in the game marks an enemy
// as moving. Enemies step on a timer (e.spd ms per tile), so a tile change opens
// a window slightly longer than one step — inside it he reads as travelling.
const dragonMotion = new Map();   // enemy id -> { x, y, until }

function dragonIsMoving(e) {
  const now = Date.now();
  let m = dragonMotion.get(e.id);
  if (!m) { m = { x: e.x, y: e.y, until: 0 }; dragonMotion.set(e.id, m); }
  if (m.x !== e.x || m.y !== e.y) {
    m.x = e.x; m.y = e.y;
    m.until = now + (e.spd || 500) * 1.15;
  }
  return now < m.until;
}

// Which animation the dragon's current state maps to. Only `dormant` and
// `breathe` come from real flags (e.dormant, e.breathT); the rest are derived
// from distance and movement, because the game tracks no other enemy state.
function dragonPickAnim(e) {
  if (e.dormant) return 'dormant';
  if (e.breathT > 0) return 'breathe';
  if (typeof player !== 'undefined') {
    const dx = player.x - e.x, dy = player.y - e.y;
    const d  = Math.sqrt(dx * dx + dy * dy);
    if (d <= DRAGON_MELEE_RANGE) return 'fight';
    if (dragonIsMoving(e)) return d > DRAGON_FLY_RANGE ? 'fly' : 'run';
  }
  return 'awake';
}

// Blit the current dragon frame so its body box lands exactly on (bx, by, s, s)
// — the same box the procedural art draws into, i.e. px/py and s = ts * e.size.
// The extra margin is overhang for the crown, wings and lashing tail.
// `t` is 0..1 progress for one-shot animations (breathe); omit it for loops.
function drawDragonSprite(bx, by, s, anim, phase, t) {
  const [i0, n, ms] = DRAGON_ANIMS[anim];
  const fi = (t === undefined)
    ? Math.floor(Date.now() / ms + (phase || 0)) % n
    : Math.min(n - 1, Math.max(0, Math.floor(t * n)));
  const idx = i0 + fi;
  const k  = s / DRAGON_BODY;
  const dw = DRAGON_FRAME * k;
  const smoothing = ctx.imageSmoothingEnabled;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(
    dragonSheetImg,
    (idx % DRAGON_COLS) * DRAGON_FRAME,
    Math.floor(idx / DRAGON_COLS) * DRAGON_FRAME,
    DRAGON_FRAME, DRAGON_FRAME,
    bx - DRAGON_BODY_O * k, by - DRAGON_BODY_O * k, dw, dw);
  ctx.imageSmoothingEnabled = smoothing;
}

ensureDragonSheet();
