// GENERATED by tools/make-hero-sheet.lua. Do not edit by hand.
//
// Regenerate with the two commands in that script's header, from the
// repo root. This file is written by step 1, alongside the .aseprite.
//
// Loaded as a plain script (no modules, no fetch) so it works from
// file://, and read by hero-sprite.js.
const HERO_ATLAS = {
  frame: 96,
  body: 48,
  bodyOX: 24,
  bodyOY: 24,
  footF: 0.96,
  cols: 52,
  dirRow: { down: 0, up: 1, left: 2, right: 3 },
  anims: {
    idle: [0, 2, 280],
    walk: [2, 4, 110],
    punch: [6, 4, 37],
    jump: [10, 4, 90],
    swim: [14, 4, 140],
    climb: [18, 4, 110],
    idle_armed: [22, 2, 280],
    walk_armed: [24, 4, 110],
    jump_armed: [28, 4, 90],
    idle_bow: [32, 2, 280],
    walk_bow: [34, 4, 110],
    jump_bow: [38, 4, 90],
    bow: [42, 5, 56],
    sword: [47, 5, 36],
  },
};
