// ─── Hero sprite sheet ────────────────────────────────────────────────────────
// Loads hero-sheet.png and hands drawPlayer() a single blit per frame in place
// of its procedural body. The art is generated by tools/make-hero-sheet.lua from
// the painted character portrait (hero-portrait.png).
//
// The frame layout comes from hero-atlas.js, which that same generator writes.
// It used to be a hardcoded copy of the generator's constants with a comment
// asking the next person to remember to change both, which is a drift hazard
// with no upside. The atlas is a .js file assigning a global rather than the
// .json Aseprite emits, because the game is opened from file://, where fetch and
// XHR cannot read a sibling file.
//
// Loading is async and failure is survivable. Until the image is ready, and
// forever if it 404s, drawPlayer falls back to its original procedural sprite.
// That matches how stats.js treats hero-portrait.png. A missing or malformed
// atlas takes the same route: heroSheetReady() reports false and the procedural
// hero draws, rather than the game dying on a bad property read.

const HERO_SHEET_SRC = 'hero-sheet.png';

// The unarmed anims are used until player.hasSword flips in prologue Beat 5.
// render.js is explicit that no blade may be drawn before the player owns one,
// so those poses carry no sword. Bow, jump, swim, and climb are authored states
// in the same sheet rather than procedural overlays, keeping the silhouette
// consistent with the portrait-inspired idle and walk frames.
const HERO_ATLAS_OK = typeof HERO_ATLAS !== 'undefined' && !!HERO_ATLAS &&
                      !!HERO_ATLAS.anims && !!HERO_ATLAS.dirRow &&
                      HERO_ATLAS.frame > 0 && HERO_ATLAS.body > 0;

const HERO_FRAME   = HERO_ATLAS_OK ? HERO_ATLAS.frame  : 64;
const HERO_BODY    = HERO_ATLAS_OK ? HERO_ATLAS.body   : 48;
const HERO_BODY_OX = HERO_ATLAS_OK ? HERO_ATLAS.bodyOX : 8;
const HERO_BODY_OY = HERO_ATLAS_OK ? HERO_ATLAS.bodyOY : 7;
// Frames per DIRECTION, and frames per SHEET ROW. They are the same number
// only while a direction's whole run fits on one row of the PNG; at a 128px
// frame, 52 columns would be a 6656px-wide texture, which is past where mobile
// GPUs stop hardware-accelerating a drawImage source, so the generator wraps a
// direction across two rows of 26. `perDir` is the anim layout, `sheetCols` is
// the image layout, and heroFrameXY below is the only place that knows both.
//
// Both fall back to the older atlas's single `cols`, so an atlas emitted before
// the wrap existed still indexes correctly: with sheetCols === perDir the
// division collapses to the row-per-direction arithmetic it replaced.
const HERO_PER_DIR   = HERO_ATLAS_OK ? (HERO_ATLAS.perDir    ?? HERO_ATLAS.cols) : 52;
const HERO_SHEET_COLS = HERO_ATLAS_OK ? (HERO_ATLAS.sheetCols ?? HERO_PER_DIR)   : 52;
// Blade reach for the swing, in BODY pixels, used to place the elemental sword
// FX at the tip. Shipped by the generator rather than copied here — it grew
// from 30 to 35 when the figure did, and a stale copy would leave the FX
// bursting from the middle of the blade.
const HERO_SWORD_LEN = (HERO_ATLAS_OK && typeof HERO_ATLAS.swordLen === 'number')
  ? HERO_ATLAS.swordLen : 30;
// Where the boot soles sit, as a fraction down the body box. 0.96, not 1.0: the
// character does not quite fill her own box. Defaulted to 1.0 rather than 0.96
// when the atlas is missing, because 1.0 is the "plant the box bottom" rule the
// renderer used before this existed, and a fallback should reproduce the old
// behaviour rather than guess at art it cannot see.
const HERO_FOOT_F  = (HERO_ATLAS_OK && typeof HERO_ATLAS.footF === 'number')
  ? HERO_ATLAS.footF : 1.0;
const HERO_DIR_ROW = HERO_ATLAS_OK ? HERO_ATLAS.dirRow : { down: 0, up: 1, left: 2, right: 3 };
const HERO_ANIMS   = HERO_ATLAS_OK ? HERO_ATLAS.anims  : {};

const HERO_PUNCH_MS = 150;    // must match doPunch in player.js
const HERO_SWORD_MS = 180;    // must match doSword in player.js
const HERO_BOW_MS   = 280;     // must match firePlayerArrow in projectiles.js

let heroSheetImg   = null;
let heroSheetState = 'idle';  // 'idle' | 'loading' | 'ready' | 'error'

function ensureHeroSheet() {
  if (!HERO_ATLAS_OK) return;
  if (heroSheetImg) return;
  heroSheetImg = new Image();
  heroSheetState = 'loading';
  heroSheetImg.onload  = () => { heroSheetState = 'ready'; };
  heroSheetImg.onerror = () => { heroSheetState = 'error'; };
  heroSheetImg.src = HERO_SHEET_SRC;
}

function heroSheetReady() {
  // No atlas, no sheet path. The blit indexes frames by the atlas's numbers, so
  // without them there is nothing to index and the procedural hero is correct.
  if (!HERO_ATLAS_OK) return false;
  ensureHeroSheet();
  return heroSheetState === 'ready';
}

// Which animation the player's current state maps to, and how far through it.
// Returns [animName, t] where t is 0..1 for one-shot actions, or null for the
// looping idle/walk cycles (those run off the wall clock instead).
function heroPickAnim(moving) {
  const armed = !!player.hasSword;
  const bowing = !!player.hasBow && player.weapon === 'bow';
  if (player.swordTimer > 0) {
    return ['sword', 1 - Math.max(0, Math.min(1, player.swordTimer / HERO_SWORD_MS))];
  }
  if (player.punchTimer > 0) {
    return ['punch', 1 - Math.max(0, Math.min(1, player.punchTimer / HERO_PUNCH_MS))];
  }
  if (player.bowTimer > 0) {
    return ['bow', 1 - Math.max(0, Math.min(1, player.bowTimer / HERO_BOW_MS))];
  }

  // A positive player.z is the simulation's hop/fall height. groundZ is a ledge
  // surface, not an airborne state, so deliberately do not include it here.
  if ((player.z || 0) > 0.035) {
    return [bowing ? 'jump_bow' : (armed ? 'jump_armed' : 'jump'), null];
  }

  const tile = (typeof mapData === 'function') ? mapData() : null;
  const tileHere = tile && tile[player.y] ? tile[player.y][player.x] : null;
  if (typeof T !== 'undefined' && tileHere === T.MEDIUM_WATER) {
    return ['swim', null];
  }
  if (typeof T !== 'undefined' && tileHere === T.CLIMB && moving) {
    return [armed ? 'climb_armed' : 'climb', null];
  }

  if (bowing) return [moving ? 'walk_bow' : 'idle_bow', null];
  if (moving) return [armed ? 'walk_armed' : 'walk', null];
  return [armed ? 'idle_armed' : 'idle', null];
}

// Screen top-left of the hero's BODY box, given the tile box at (sx, sy, s, s).
//
// The body box is placed so the FOOT ROW lands on the tile's bottom edge, not so
// the box bottom does. Those differ by (1 - footF) of a tile, which is 2px at
// TILE_PX 48: the hero used to float by exactly that much, because the art's
// soles stop at 0.96 while the renderer planted 1.00.
//
// Shared with heroSwordTip so the blade FX cannot anchor to a different origin
// than the body it is supposed to be held by.
function heroBodyOrigin(sx, sy, s) {
  return { x: sx, y: sy + s * (1 - HERO_FOOT_F) };
}

// Top-left of one frame in the sheet, given a facing and a column within that
// facing's run. The sheet is laid out as one flat sequence of frames — all of
// `down`, then all of `up`, and so on — wrapped every HERO_SHEET_COLS frames,
// so a direction does not necessarily start at the left edge of a row and does
// not necessarily end on the same row it started.
//
// This used to be inline as `col * FRAME, dirRow * FRAME`, which silently
// assumed one row per direction. That held while the sheet was 52 columns wide
// and stopped holding the moment it wrapped.
function heroFrameXY(facing, col) {
  const i = HERO_DIR_ROW[facing] * HERO_PER_DIR + col;
  return { x: (i % HERO_SHEET_COLS) * HERO_FRAME,
           y: Math.floor(i / HERO_SHEET_COLS) * HERO_FRAME };
}

// Blit the current hero frame so its 48px body box lands on the tile box at
// (sx, sy, s, s), foot row on the ground. The body box is her FOOTPRINT, not her
// height: she stands about 0.94 boxes tall and the frame is twice the body to
// hold that plus a raised blade. All of that surplus is deliberate overhang
// (raised blade, ear tips, cloak, downward swings) and is allowed to spill
// outside the tile.
function drawHeroSprite(sx, sy, s, facing, moving) {
  const [requestedAnim, t] = heroPickAnim(moving);
  // A stale sheet/atlas pair should degrade to a known idle frame rather than
  // throwing from an undefined animation tuple and taking down the render loop.
  const anim = HERO_ANIMS[requestedAnim] ? requestedAnim :
    (player.hasSword ? 'idle_armed' : 'idle');
  const [col0, n, ms] = HERO_ANIMS[anim];
  const fi = (t === null)
    ? Math.floor(Date.now() / ms) % n
    : Math.min(n - 1, Math.max(0, Math.floor(t * n)));

  const k  = s / HERO_BODY;
  const dw = HERO_FRAME * k;
  const org = heroBodyOrigin(sx, sy, s);
  const src = heroFrameXY(facing, col0 + fi);
  const smoothing = ctx.imageSmoothingEnabled;
  ctx.imageSmoothingEnabled = false;      // keep the pixel art crisp at any zoom
  ctx.drawImage(
    heroSheetImg,
    src.x, src.y, HERO_FRAME, HERO_FRAME,
    org.x - HERO_BODY_OX * k, org.y - HERO_BODY_OY * k, dw, dw);
  ctx.imageSmoothingEnabled = smoothing;
}

// Where the blade tip sits for the current swing frame, so elemental sword FX
// can still burst from it. The sheet is one flat image and can't be tinted.
function heroSwordTip(sx, sy, s) {
  const sd = player.swordDir;
  const phase = 1 - Math.max(0, Math.min(1, player.swordTimer / HERO_SWORD_MS));
  const a = Math.atan2(sd.y, sd.x) - (Math.PI * 0.85) / 2 + (Math.PI * 0.85) * phase;
  // SW_LEN in the generator, a length in BODY pixels, and so unchanged by the
  // frame growing around it. Read from the atlas rather than repeated here:
  // it was the literal 30 while the generator also said 30, and the generator
  // now says 35. Still shorter than the 1.25 tiles the hitbox reaches.
  const len = s * (HERO_SWORD_LEN / HERO_BODY);
  // Anchored on the body box, not the tile box, so the tip follows the same 2px
  // foot-anchoring shift the sprite does.
  const org = heroBodyOrigin(sx, sy, s);
  return { x: org.x + s / 2 + Math.cos(a) * len, y: org.y + s / 2 + Math.sin(a) * len };
}

// Start the download at load time rather than on the first drawPlayer call, so
// gameplay's opening frames already have it and the procedural fallback doesn't
// flash for a frame or two when a map first appears.
ensureHeroSheet();
