// ─── Hero sprite sheet ────────────────────────────────────────────────────────
// Loads hero-sheet.png and hands drawPlayer() a single blit per frame in place
// of its procedural body. The art is generated by tools/make-hero-sheet.lua from
// the painted character portrait (hero-portrait.png).
//
// The frame layout below is hardcoded to mirror that generator. It deliberately
// does NOT read hero-sheet.json at runtime: the game is opened from file://,
// where fetch/XHR cannot touch a sibling file. If you change the generator's
// KINDS table or frame counts, change these constants in the same edit.
//
// Loading is async and failure is survivable — until the image is ready, and
// forever if it 404s, drawPlayer falls back to its original procedural sprite.
// That matches how stats.js treats hero-portrait.png.

const HERO_SHEET_SRC = 'hero-sheet.png';
const HERO_FRAME     = 64;   // frame box in the sheet, px
const HERO_BODY      = 48;   // body box inside that frame == one map tile
const HERO_BODY_OX   = 8;    // body box origin inside the frame
const HERO_BODY_OY   = 7;
const HERO_COLS      = 21;   // frames per direction; one sheet row per direction

// Sheet rows, in the generator's DIRS order.
const HERO_DIR_ROW = { down: 0, up: 1, left: 2, right: 3 };

// anim -> [startColumn, frameCount, msPerFrame]. The unarmed set is used until
// player.hasSword flips in prologue Beat 5 — render.js is explicit that no blade
// may be drawn before the player owns one, so those poses carry no sword.
const HERO_ANIMS = {
  idle:       [0,  2, 280],
  walk:       [2,  4, 110],
  punch:      [6,  4,  37],   // player.punchTimer runs 150ms
  idle_armed: [10, 2, 280],
  walk_armed: [12, 4, 110],
  sword:      [16, 5,  36],   // player.swordTimer runs 180ms
};

const HERO_PUNCH_MS = 150;    // must match doPunch in player.js
const HERO_SWORD_MS = 180;    // must match doSword in player.js

let heroSheetImg   = null;
let heroSheetState = 'idle';  // 'idle' | 'loading' | 'ready' | 'error'

function ensureHeroSheet() {
  if (heroSheetImg) return;
  heroSheetImg = new Image();
  heroSheetState = 'loading';
  heroSheetImg.onload  = () => { heroSheetState = 'ready'; };
  heroSheetImg.onerror = () => { heroSheetState = 'error'; };
  heroSheetImg.src = HERO_SHEET_SRC;
}

function heroSheetReady() {
  ensureHeroSheet();
  return heroSheetState === 'ready';
}

// Which animation the player's current state maps to, and how far through it.
// Returns [animName, t] where t is 0..1 for one-shot actions, or null for the
// looping idle/walk cycles (those run off the wall clock instead).
function heroPickAnim(moving) {
  const armed = !!player.hasSword;
  if (player.swordTimer > 0) {
    return ['sword', 1 - Math.max(0, Math.min(1, player.swordTimer / HERO_SWORD_MS))];
  }
  if (player.punchTimer > 0) {
    return ['punch', 1 - Math.max(0, Math.min(1, player.punchTimer / HERO_PUNCH_MS))];
  }
  if (moving) return [armed ? 'walk_armed' : 'walk', null];
  return [armed ? 'idle_armed' : 'idle', null];
}

// Blit the current hero frame so its 48px body box lands exactly on the tile box
// at (sx, sy, s, s). The extra 16px of frame is deliberate overhang — raised
// blade, ear tips, cloak — and is allowed to spill outside the tile.
function drawHeroSprite(sx, sy, s, facing, moving) {
  const [anim, t] = heroPickAnim(moving);
  const [col0, n, ms] = HERO_ANIMS[anim];
  const fi = (t === null)
    ? Math.floor(Date.now() / ms) % n
    : Math.min(n - 1, Math.max(0, Math.floor(t * n)));

  const k  = s / HERO_BODY;
  const dw = HERO_FRAME * k;
  const smoothing = ctx.imageSmoothingEnabled;
  ctx.imageSmoothingEnabled = false;      // keep the pixel art crisp at any zoom
  ctx.drawImage(
    heroSheetImg,
    (col0 + fi) * HERO_FRAME, HERO_DIR_ROW[facing] * HERO_FRAME, HERO_FRAME, HERO_FRAME,
    sx - HERO_BODY_OX * k,    sy - HERO_BODY_OY * k,             dw,         dw);
  ctx.imageSmoothingEnabled = smoothing;
}

// Where the blade tip sits for the current swing frame, so elemental sword FX
// can still burst from it — the sheet is one flat image and can't be tinted.
function heroSwordTip(sx, sy, s) {
  const sd = player.swordDir;
  const phase = 1 - Math.max(0, Math.min(1, player.swordTimer / HERO_SWORD_MS));
  const a = Math.atan2(sd.y, sd.x) - (Math.PI * 0.85) / 2 + (Math.PI * 0.85) * phase;
  // 30/48 of a tile: the sheet's blade reach, shorter than the 1.25 tiles the
  // hitbox uses, because the full reach does not fit in a 64px frame.
  const len = s * (30 / HERO_BODY);
  return { x: sx + s / 2 + Math.cos(a) * len, y: sy + s / 2 + Math.sin(a) * len };
}

// Start the download at load time rather than on the first drawPlayer call, so
// gameplay's opening frames already have it and the procedural fallback doesn't
// flash for a frame or two when a map first appears.
ensureHeroSheet();
