// GENERATED by tools/make-village-sheet.lua. Do not edit by hand.
//
// Regenerate with the two commands in that script's header, from the
// repo root. This file is written by step 1, alongside the .aseprite.
//
// Loaded as a plain script (no modules, no fetch) so it works from
// file://, and read by village-sprite.js.
const VILLAGE_ATLAS = {
  tile: 48,
  cols: 3,
  frames: {
    roof_nw: 0,
    roof_n: 1,
    roof_ne: 2,
    roof_w: 3,
    roof_c: 4,
    roof_e: 5,
    ridge_w: 6,
    ridge_c: 7,
    ridge_e: 8,
    roof_sw: 9,
    roof_s: 10,
    roof_se: 11,
    fascia_w: 12,
    fascia_c: 13,
    fascia_e: 14,
    wall_cap: 15,
    wall_face: 16,
    door_face: 17,
    pillar_cap: 18,
    spout: 19,
    basin: 20,
    basin_edge: 21,
  },
};
