// GENERATED by tools/make-villager-sheet.lua. Do not edit by hand.
const VILLAGER_ATLAS = {
  frame: 96,
  body: 48,
  bodyOX: 24,
  bodyOY: 24,
  footF: 0.96,
  perDir: 6,
  sheetCols: 24,
  dirRow: { down: 0, up: 1, left: 2, right: 3 },
  anims: {
    idle: [0, 2, 400],
    walk: [2, 4, 130],
  },
};
