// ─── Forest village building sheet ────────────────────────────────────────────
// Loads village-sheet.png and re-skins the forest villages' buildings and
// fountain from it, in place of the procedural roof planes, wall art and flat
// blue basin. The art is generated by tools/make-village-sheet.lua from the
// village concept sketches in concept-art/village-layouts/.
//
// The frame layout comes from village-atlas.js, which that same generator
// writes — a .js file assigning a global rather than the .json Aseprite emits,
// because the game is opened from file:// where fetch and XHR cannot read a
// sibling file. Same arrangement as hero-atlas.js / hero-sprite.js.
//
// Loading is async and failure is survivable. Until the image is ready, and
// forever if it 404s, every entry point here reports "not mine" and the caller
// draws exactly what it drew before this file existed. A missing or malformed
// atlas takes the same route rather than dying on a bad property read.
//
// SCOPE. This is the pilot re-skin, and it is deliberately narrow:
//
//   • Forest villages only — Village of the Lost (type 'village') and
//     Elderbrook (type 'homevillage'). Every other biome's village keeps its
//     region palette, which is what makes an ice or volcanic village read as
//     one. villageArtActive is the single gate.
//   • Buildings and the fountain only. Grass, cobble, marble, flowers and the
//     tree border stay procedural, so a village still blends into the overworld
//     around it instead of ending at a hard seam.
//   • Elderbrook's family home is NOT touched. Its bespoke projected facade
//     (the familyHome branch of drawForestHouseRoof) is the prologue's set
//     piece and is tuned against beats this sheet knows nothing about.

const VILLAGE_SHEET_SRC = 'village-sheet.png';

const VILLAGE_ATLAS_OK = typeof VILLAGE_ATLAS !== 'undefined' && !!VILLAGE_ATLAS &&
                         !!VILLAGE_ATLAS.frames && VILLAGE_ATLAS.tile > 0 &&
                         VILLAGE_ATLAS.cols > 0;

const VILLAGE_TILE = VILLAGE_ATLAS_OK ? VILLAGE_ATLAS.tile : 48;
const VILLAGE_COLS = VILLAGE_ATLAS_OK ? VILLAGE_ATLAS.cols : 3;
const VILLAGE_F    = VILLAGE_ATLAS_OK ? VILLAGE_ATLAS.frames : {};

let villageSheetImg   = null;
let villageSheetState = 'idle';   // 'idle' | 'loading' | 'ready' | 'error'

function ensureVillageSheet() {
  if (!VILLAGE_ATLAS_OK) return;
  if (villageSheetImg) return;
  villageSheetImg = new Image();
  villageSheetState = 'loading';
  villageSheetImg.onload  = () => { villageSheetState = 'ready'; };
  villageSheetImg.onerror = () => { villageSheetState = 'error'; };
  villageSheetImg.src = VILLAGE_SHEET_SRC;
}

function villageSheetReady() {
  if (!VILLAGE_ATLAS_OK) return false;
  ensureVillageSheet();
  return villageSheetState === 'ready';
}

// The one gate. Every entry point below asks this before drawing a single
// pixel, so widening or narrowing the pilot is a change to this function alone.
//
// Deliberately the same map test roofsApply (render.js) already makes, minus
// its Ashfall clause: a burnt Elderbrook has no intact roofs, but its walls and
// its fountain are still there, and they are still the forest village's.
function villageArtActive(mapObj) {
  if (!villageSheetReady()) return false;
  if (!mapObj || mapObj.biome !== 'forest') return false;
  return mapObj.type === 'village' || mapObj.type === 'homevillage';
}

function villageArtHere() {
  return typeof currentMap === 'function' && villageArtActive(currentMap());
}

// Blit one named frame into the destination rect. Nearest-neighbour, like the
// hero sheet: the art is authored at 48 and the game runs at TILE_PX 24 as well
// as 48, and smoothing turns a 1px ink line into grey mush at the smaller size.
function vBlit(name, dx, dy, dw, dh) {
  const f = VILLAGE_F[name];
  if (f === undefined) return;
  const T = VILLAGE_TILE;
  const smoothing = ctx.imageSmoothingEnabled;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(villageSheetImg,
    (f % VILLAGE_COLS) * T, Math.floor(f / VILLAGE_COLS) * T, T, T,
    dx, dy, dw, dh);
  ctx.imageSmoothingEnabled = smoothing;
}

// Same, rotated in quarter turns about the destination square's centre. Only
// basin_edge uses this: its marble lip is authored along the north edge and
// turned for the other three, which is why that frame carries nothing that
// reads as up.
function vBlitTurned(name, dx, dy, size, turns) {
  if (!turns) { vBlit(name, dx, dy, size, size); return; }
  ctx.save();
  ctx.translate(dx + size / 2, dy + size / 2);
  ctx.rotate(turns * Math.PI / 2);
  vBlit(name, -size / 2, -size / 2, size, size);
  ctx.restore();
}

// Repeat a frame at its native scale across a rect, clipped to it.
//
// Tiling rather than stretching is the whole reason the roof reads as material:
// a house is an arbitrary pixel rect (it carries fractional eave overhang), and
// stretching a shingle course to fit would give every cottage a different
// shingle size. Clipping cuts the last row and column instead, which is what
// the dark frame beams then cover.
function vTileRegion(name, x0, y0, x1, y1, ts) {
  if (x1 - x0 < 0.5 || y1 - y0 < 0.5) return;
  ctx.save();
  ctx.beginPath();
  ctx.rect(x0, y0, x1 - x0, y1 - y0);
  ctx.clip();
  for (let y = y0; y < y1; y += ts)
    for (let x = x0; x < x1; x += ts)
      vBlit(name, x, y, ts, ts);
  ctx.restore();
}

// ─── Roof ─────────────────────────────────────────────────────────────────────
// Draw one cottage roof from the sheet, over the pixel rect drawForestHouseRoof
// already computed. Returns false if it declined, and the caller then draws its
// own planes exactly as before.
//
// The roof is five horizontal bands read top to bottom — north eave, north
// slope, ridge, south slope, south fascia — each split into a west piece, a
// tiled centre, and an east piece. The three fixed-height bands are one tile
// tall each; the two slopes take whatever is left. That is why a roof shorter
// than ~3.4 tiles is refused below: the bands would overlap and the ridge would
// land inside the eave.
const VILLAGE_ROOF_MIN_H = 3.4;    // tiles, for eave + ridge + fascia + slopes
const VILLAGE_ROOF_MIN_W = 2.4;    // tiles, for two verges plus something between

function drawVillageRoofPlanes(left, top, right, roofBottom, ridgeY, ts) {
  if (!villageSheetReady()) return false;
  const w = right - left, h = roofBottom - top;
  if (w < VILLAGE_ROOF_MIN_W * ts || h < VILLAGE_ROOF_MIN_H * ts) return false;

  // Keep the ridge inside the slopes even if the caller's 43% lands it close to
  // an end. Clamped rather than refused: a squat cottage should still get the
  // sheet, just with a shorter slope above or below its ridge.
  const half = ts / 2;
  const ridgeMid = Math.max(top + ts + half, Math.min(roofBottom - ts - half, ridgeY));
  const ridgeTop = ridgeMid - half, ridgeBot = ridgeMid + half;

  const bands = [
    ['roof_nw',  'roof_n',   'roof_ne',  top,                top + ts],
    ['roof_w',   'roof_c',   'roof_e',   top + ts,           ridgeTop],
    ['ridge_w',  'ridge_c',  'ridge_e',  ridgeTop,           ridgeBot],
    ['roof_sw',  'roof_s',   'roof_se',  ridgeBot,           roofBottom - ts],
    ['fascia_w', 'fascia_c', 'fascia_e', roofBottom - ts,    roofBottom],
  ];

  for (const [wf, cf, ef, y0, y1] of bands) {
    vTileRegion(wf, left,      y0, left + ts,  y1, ts);
    vTileRegion(cf, left + ts, y0, right - ts, y1, ts);
    vTileRegion(ef, right - ts, y0, right,     y1, ts);
  }
  return true;
}

// The small gable over a cottage door. drawForestHouseRoof draws this as one
// flat triangle in its own brown, which against sheet shingles reads as a
// plastic cone stuck to the roof rather than as part of the building. Same
// material, then: south-slope shingles clipped to the same triangle, a shade
// darker because this plane faces the player instead of the sky.
const VILLAGE_INK = '#0c0907';   // the concept sketches' near-black outline

function drawVillageGable(centreX, peakY, half, baseY, ts) {
  if (!villageSheetReady()) return false;
  if (half <= 0 || baseY <= peakY) return false;

  ctx.save();
  ctx.beginPath();
  ctx.moveTo(centreX, peakY);
  ctx.lineTo(centreX + half, baseY);
  ctx.lineTo(centreX - half, baseY);
  ctx.closePath();
  ctx.clip();
  for (let y = peakY; y < baseY; y += ts)
    for (let x = centreX - half; x < centreX + half; x += ts)
      vBlit('roof_s', x, y, ts, ts);
  ctx.fillStyle = 'rgba(20,10,4,0.24)';
  ctx.fillRect(centreX - half, peakY, half * 2, baseY - peakY);
  ctx.restore();

  // Rake boards down both slopes and the hip beam on the centre line, in the
  // ridge's own timber colours so the gable and the ridge read as one carpentry.
  ctx.strokeStyle = VILLAGE_INK;
  ctx.lineWidth = Math.max(1.5, ts * 0.07);
  ctx.beginPath();
  ctx.moveTo(centreX - half, baseY);
  ctx.lineTo(centreX, peakY);
  ctx.lineTo(centreX + half, baseY);
  ctx.stroke();
  ctx.strokeStyle = '#c9a86e';
  ctx.lineWidth = Math.max(1, ts * 0.055);
  ctx.beginPath();
  ctx.moveTo(centreX, peakY + ts * 0.16);
  ctx.lineTo(centreX, baseY - ts * 0.10);
  ctx.stroke();
  return true;
}

// ─── Walls ────────────────────────────────────────────────────────────────────
// A wall's top, seen from directly above. This is what a house shows in Village
// of the Lost once the player steps inside and the roof lifts, and it is also
// the cap of an extruded wall on Elderbrook.
function drawVillageWallCap(x, y, ts) {
  if (!villageSheetReady()) return false;
  vBlit('wall_cap', x, y, ts, ts);
  return true;
}

// The side of an extruded wall: vertical boards repeated down the face band.
// The caller keeps its own gradient and edge shading on top, so a tall face
// still grades from its cap to the ground the way every other extrusion does.
function drawVillageWallFace(x, faceTop, ts, lift) {
  if (!villageSheetReady()) return false;
  vTileRegion('wall_face', x, faceTop, x + ts, faceTop + lift, ts);
  return true;
}

// The door panel at the foot of an extruded wall face.
function drawVillageDoorPanel(x, y, ts) {
  if (!villageSheetReady()) return false;
  vBlit('door_face', x, y, ts, ts);
  return true;
}

// ─── The cottage facade's material (item A) ───────────────────────────────────
// Until now `wall_face` and `door_face` were reachable only through the
// extrusion path, which runs on the Elderbrook pilot alone. A cottage's
// projected front elevation is the same surface seen the same way, so it takes
// the same two frames rather than a second set authored to match them.
//
// Tiled, not stretched, for the reason vTileRegion exists: a facade is an
// arbitrary pixel rect and stretching would give every house a different plank
// width. The caller keeps its own eave shadow, frame and sill on top.
function drawVillageFacadeWall(x0, y0, x1, y1, ts) {
  if (!villageSheetReady()) return false;
  if (x1 - x0 < 0.5 || y1 - y0 < 0.5) return false;
  vTileRegion('wall_face', x0, y0, x1, y1, ts);
  return true;
}

// The door panel at an explicit rect. drawVillageDoorPanel above is a square
// tile blit because that is what an extruded wall's foot is; a facade door is
// its own opening, taller than it is wide, so the caller sizes it.
function drawVillageDoorPanelRect(x, y, w, h) {
  if (!villageSheetReady()) return false;
  if (w < 0.5 || h < 0.5) return false;
  vBlit('door_face', x, y, w, h);
  return true;
}

// ─── Fountain and tile-pass art ───────────────────────────────────────────────
// Called from drawTile BEFORE the sprite cache, and it must stay there. The
// cache keys art on tile type alone, so a village-only look for T.WALL or
// T.PILLAR baked into it would follow those tiles onto every other map. Every
// frame these blits use is a full opaque tile for exactly the same reason
// drawTile returning early demands it: nothing else paints a base square.
//
// Returns true when it has drawn the tile and the caller should stop.
function villageTileArt(col, row, t, sx, sy, s) {
  if (!villageArtHere()) return false;

  const x = Math.floor(sx), y = Math.floor(sy);

  if (t === T.WALL) { vBlit('wall_cap', x, y, s, s); return true; }

  // The colonnade around the basin. The column frame is transparent around the
  // stone, so the plaza has to go down first — and it has to be the REAL marble
  // tile, not a flat fill, because T.MARBLE is a hashed variant with eight vein
  // patterns and a plain square would leave every column on a visibly veinless
  // patch. Re-entering drawTile is safe and terminates: this function declines
  // T.MARBLE on the way back in.
  if (t === T.PILLAR) {
    drawTile(col, row, T.MARBLE, sx, sy, s);
    vBlit('pillar_cap', x, y, s, s);
    return true;
  }

  if (t === T.FOUNTAIN_SPOUT || t === T.FOUNTAIN_WATER) {
    vBlit(t === T.FOUNTAIN_SPOUT ? 'spout' : 'basin', x, y, s, s);
    // Marble lip wherever the basin meets something that is not basin. Drawn as
    // a transparent overlay per side, so a corner tile correctly takes two.
    const m = typeof mapData === 'function' ? mapData() : null;
    if (m) {
      const wet = (c, r) => {
        const rr = m[r];
        if (!rr) return false;
        const n = rr[c];
        return n === T.FOUNTAIN_WATER || n === T.FOUNTAIN_SPOUT;
      };
      if (!wet(col, row - 1)) vBlitTurned('basin_edge', x, y, s, 0);
      if (!wet(col + 1, row)) vBlitTurned('basin_edge', x, y, s, 1);
      if (!wet(col, row + 1)) vBlitTurned('basin_edge', x, y, s, 2);
      if (!wet(col - 1, row)) vBlitTurned('basin_edge', x, y, s, 3);
    }
    // The sheet's water is a still texture. These two drifting highlights are
    // the same wall-clock ripple the procedural FOUNTAIN_WATER case used, kept
    // so the basin does not freeze solid the moment the sheet loads.
    const sw = Math.sin(Date.now() / 500 + col * 0.5 + row * 0.4);
    ctx.fillStyle = 'rgba(191,232,245,0.34)';
    ctx.fillRect(x + s * 0.10, y + s * 0.34 + sw * 2, s * 0.42, Math.max(1, s * 0.04));
    ctx.fillStyle = 'rgba(191,232,245,0.22)';
    ctx.fillRect(x + s * 0.46, y + s * 0.64 - sw * 2, s * 0.32, Math.max(1, s * 0.04));
    return true;
  }

  return false;
}

// Start the download at load time rather than on the first village frame, so
// walking into a village does not flash one frame of procedural art first.
ensureVillageSheet();
